name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run linter
        run: |
          echo "TODO: Configure linter (eslint, pylint, clippy, etc.)"
          # Example: npm run lint
          # Example: pylint src/
          # Example: cargo clippy

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run type checker
        run: |
          echo "TODO: Configure type checker (tsc, mypy, etc.)"
          # Example: npm run typecheck
          # Example: mypy src/
          # Example: cargo check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          echo "TODO: Configure test runner (jest, pytest, cargo test, etc.)"
          # Example: npm test
          # Example: pytest --cov=src tests/
          # Example: cargo test

      - name: Upload coverage
        if: always()
        run: |
          echo "TODO: Upload coverage to codecov/coveralls if desired"
          # Example: bash <(curl -s https://codecov.io/bash)

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build project
        run: |
          echo "TODO: Configure build command"
          # Example: npm run build
          # Example: python -m build
          # Example: cargo build --release
