#!/bin/bash
# AgileFlow Development Environment Initialization
# Generated by AgileFlow session harness
# This script sets up your development environment for consistent sessions

set -e

echo "🚀 Initializing development environment..."

# Detect project type and install dependencies
# This section will be customized based on your project

# Node.js projects
if [ -f "package-lock.json" ]; then
  echo "📦 Installing dependencies (npm ci)..."
  npm ci
elif [ -f "yarn.lock" ]; then
  echo "📦 Installing dependencies (yarn)..."
  yarn install --frozen-lockfile
elif [ -f "pnpm-lock.yaml" ]; then
  echo "📦 Installing dependencies (pnpm)..."
  pnpm install --frozen-lockfile
elif [ -f "package.json" ]; then
  echo "📦 Installing dependencies (npm install)..."
  npm install
fi

# Python projects
if [ -f "requirements.txt" ]; then
  echo "📦 Installing Python dependencies..."
  pip install -r requirements.txt
fi

if [ -f "poetry.lock" ]; then
  echo "📦 Installing Poetry dependencies..."
  poetry install
fi

# Rust projects
if [ -f "Cargo.toml" ]; then
  echo "📦 Building Rust project..."
  cargo build
fi

# Go projects
if [ -f "go.mod" ]; then
  echo "📦 Downloading Go modules..."
  go mod download
fi

# Run database migrations if applicable
if [ -f "migrations/run.sh" ]; then
  echo "🗄️  Running database migrations..."
  bash migrations/run.sh
fi

if [ -d "prisma" ] && [ -f "package.json" ]; then
  if command -v npx &> /dev/null; then
    echo "🗄️  Running Prisma migrations..."
    npx prisma migrate deploy 2>/dev/null || echo "⚠️  Prisma migrations skipped"
  fi
fi

# Environment setup
if [ -f ".env.example" ] && [ ! -f ".env" ]; then
  echo "⚙️  Creating .env from .env.example..."
  cp .env.example .env
  echo "⚠️  Please configure .env with your settings"
fi

echo "✅ Environment initialization complete"
echo ""
echo "Next steps:"
echo "  - Run tests: Check environment.json for test_command"
echo "  - Start dev server: Check environment.json for dev_server.command"
echo "  - Review .env: Ensure environment variables are configured"
